spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/soundwave
    password: '12345'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
server:
  port: 8090
springfox:
  documentation:
    swagger-ui:
      base-url: myproject


